name: sovchilar_mobile
description: "A new Flutter project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Networking & API
  dio: ^5.7.0
  chuck_interceptor: ^2.2.1
  get_it: ^8.0.2
  dio_retry_plus: ^2.0.6
  go_router: ^14.6.2
  path_provider: ^2.1.2
  gap: ^3.0.1
  dropdown_button2: ^2.3.9
  pinput: ^5.0.0
  package_info_plus: ^8.1.1
  either_dart: ^1.0.0

  # Firebase
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Layout
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  flutter_image_slideshow: ^0.1.6
  syncfusion_flutter_sliders: ^28.1.38

  # Notifications
  flutter_local_notifications: ^18.0.0

  # Geolocation
  geolocator: ^13.0.2

  # Utilities
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  mask_text_input_formatter: ^2.9.0
  app_settings: ^5.1.1
  url_launcher: ^6.3.1
  device_info_plus: ^11.2.0
  image_picker: ^1.1.2
  async: ^2.11.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  firebase_ui_firestore: ^1.7.0
  carousel_slider_plus: ^7.1.0
  syncfusion_flutter_pdfviewer: ^28.1.38
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  telegram_bot_crashlytics: ^1.3.4
  mnc_identifier_face: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: 2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/default/
    - assets/locale/
    - assets/lottie/
    - assets/icon/
    - assets/pdf/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
